FROM node:20 AS builder

ARG NEXT_PUBLIC_API_ORIGIN
ARG NEXT_PUBLIC_API_KEY
ARG NEXT_PUBLIC_AUTH_DOMAIN
ARG NEXT_PUBLIC_PROJECT_ID
ARG NEXT_PUBLIC_STORAGE_BUCKET
ARG NEXT_PUBLIC_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_APP_ID
ARG NEXT_PUBLIC_MEASUREMENT_ID

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN <<EOS
echo NEXT_PUBLIC_API_ORIGIN=${NEXT_PUBLIC_API_ORIGIN} > .env
echo NEXT_PUBLIC_API_KEY=${NEXT_PUBLIC_API_KEY} >> .env
echo NEXT_PUBLIC_AUTH_DOMAIN=${NEXT_PUBLIC_AUTH_DOMAIN} >> .env
echo NEXT_PUBLIC_PROJECT_ID=${NEXT_PUBLIC_PROJECT_ID} >> .env
echo NEXT_PUBLIC_STORAGE_BUCKET=${NEXT_PUBLIC_STORAGE_BUCKET} >> .env
echo NEXT_PUBLIC_MESSAGING_SENDER_ID=${NEXT_PUBLIC_MESSAGING_SENDER_ID} >> .env
echo NEXT_PUBLIC_APP_ID=${NEXT_PUBLIC_APP_ID} >> .env
echo NEXT_PUBLIC_MEASUREMENT_ID=${NEXT_PUBLIC_MEASUREMENT_ID} >> .env
EOS

RUN npm run apigen && npm run build

FROM node:20 AS worker
WORKDIR /app

COPY --from=builder /app/.env ./.env
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3000

CMD ["node_modules/next/dist/bin/next", "start"]
