export {
  IconArrowBarToDown,
  IconCards,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconLogout,
  IconMicrophone,
  IconPencil,
  IconQrcode,
  IconSpeakerphone,
  IconUpload,
  IconExposurePlus1,
  IconSun,
  IconMoon,
  IconBrandGoogle,
  IconX,
  IconPlayerPlay,
  IconPlayerPause,
  IconCamera,
  IconBallpen,
  IconDownload,
  IconPhotoSearch,
} from '@tabler/icons-react';
